// <auto-generated />
using System;
using Inventario.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926043111_AlimentarTablaUsuario")]
    partial class AlimentarTablaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Area = "tics",
                            CorreoUsuario = "jpavel202@gmail.com",
                            FechaCreacion = new DateTime(2023, 9, 25, 22, 31, 11, 343, DateTimeKind.Local).AddTicks(6804),
                            NombreUsuario = "Pavel",
                            PasswordUsuario = "pavel12345",
                            TipoUsuario = "administrador"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Area = "tics",
                            CorreoUsuario = "Alex@gmail.com",
                            FechaCreacion = new DateTime(2023, 9, 25, 22, 31, 11, 343, DateTimeKind.Local).AddTicks(6817),
                            NombreUsuario = "Alejandro",
                            PasswordUsuario = "alex123",
                            TipoUsuario = "administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
